# statefulset-demo.yaml
# Example: StatefulSet with automatic PVC creation per pod

---
# Headless Service (required for StatefulSet)
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx-stateful
spec:
  clusterIP: None  # Headless service
  selector:
    app: nginx-stateful
  ports:
  - port: 80
    name: web

---
# StatefulSet with persistent storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx-headless  # Must match headless service name
  replicas: 3
  
  selector:
    matchLabels:
      app: nginx-stateful
  
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
          name: web
        
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        
        # Initialize with pod-specific content
        command: ['sh', '-c']
        args:
        - |
          # Write pod hostname to index.html
          echo "<h1>Hello from $HOSTNAME</h1>" > /usr/share/nginx/html/index.html
          echo "<p>This data persists across pod restarts</p>" >> /usr/share/nginx/html/index.html
          echo "<p>Timestamp: $(date)</p>" >> /usr/share/nginx/html/index.html
          
          # Start nginx
          nginx -g 'daemon off;'
  
  # VolumeClaimTemplate: creates PVC for each pod automatically
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

# Key StatefulSet features:
# 1. Stable pod names: web-0, web-1, web-2 (not random like Deployment)
# 2. Ordered creation: web-0 must be ready before web-1 starts
# 3. Automatic PVC: Creates www-web-0, www-web-1, www-web-2
# 4. Stable storage: Pod web-0 always uses www-web-0 PVC

# Usage:
# kubectl apply -f statefulset-demo.yaml
#
# Watch ordered creation:
# kubectl get pods -w
#
# Check PVCs:
# kubectl get pvc
# # www-web-0, www-web-1, www-web-2
#
# Check pod-specific data:
# kubectl exec web-0 -- cat /usr/share/nginx/html/index.html
# kubectl exec web-1 -- cat /usr/share/nginx/html/index.html
# kubectl exec web-2 -- cat /usr/share/nginx/html/index.html
#
# Delete a pod:
# kubectl delete pod web-1
# # StatefulSet recreates web-1 (same name) and uses www-web-1 PVC
#
# Scale down:
# kubectl scale statefulset web --replicas=1
# # Deletes web-2, then web-1 (reverse order)
# # PVCs are NOT deleted automatically
#
# Cleanup:
# kubectl delete statefulset web
# kubectl delete service nginx-headless
# kubectl delete pvc www-web-0 www-web-1 www-web-2
