# pod-with-secrets.yaml
# Example: Using Secrets as environment variables

apiVersion: v1
kind: Pod
metadata:
  name: app-with-secrets
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: busybox:1.36
    command:
    - sh
    - -c
    - |
      echo "=== Connecting to Services ==="
      echo "Database Password: $DB_PASSWORD"
      echo "API Key: $API_KEY"
      echo "JWT Secret: $JWT_SECRET"
      echo ""
      echo "WARNING: Never log secrets in production!"
      echo "This is for learning only."
      echo ""
      sleep 3600
    
    # Environment variables from Secret
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: database_password
    
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api_key
    
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: jwt_secret
    
    # Alternative: Load all keys as env vars
    # envFrom:
    # - secretRef:
    #     name: app-secrets

# Create Secret first:
# kubectl create secret generic app-secrets \
#   --from-literal=database_password="super_secret_password" \
#   --from-literal=api_key="sk_live_abc123xyz456" \
#   --from-literal=jwt_secret="my-jwt-secret-key-2024"
#
# Then apply pod:
# kubectl apply -f pod-with-secrets.yaml
#
# Check logs:
# kubectl logs app-with-secrets
